In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# import self-made module
import os, sys, pathlib
file_path = os.path.abspath('')
PROJECT_DIR = str(pathlib.Path(file_path).parent)
sys.path.append(PROJECT_DIR)
print(f"Added {PROJECT_DIR} to PATH")
from athena import *
from sympy.vector import CoordSys3D, gradient, curl, ParametricRegion, vector_integrate, scalar_potential
from sympy.integrals.manualintegrate import integral_steps

sp.init_printing()

# ult functions
def reset_symbols():
    global x, y, z, a, b, c, d, e, f, g, h, r, s, k, t, u, v, theta, lmda, rho, phi
    x, y, z = sp.symbols('x y z', real=True)
    a, b, c, d, e, f, g, h, r, s, k, t, u, v = sp.symbols('a b c d e f g h r s k t u v', real=True)
    theta = sp.Symbol('theta')
    lmda = sp.Symbol('lambda')
    rho = sp.Symbol('rho')
    phi = sp.Symbol('phi')
    

reset_symbols()

import statistics
import math
import numpy as np
import scipy

Added D:\Dev\Code\MyMathLab to PATH


In [3]:
1 - scipy.stats.chi2.cdf(2.41, 2)

In [7]:
obs_ls = [30, 14, 34, 45, 57, 20]
exp_ls = [20, 20, 30, 40, 60, 30]
scipy.stats.chisquare(obs_ls, exp_ls)

Power_divergenceResult(statistic=11.441666666666666, pvalue=0.04329313031580497)

In [8]:
obs_ls = [20,20,25,35]
exp_ls = [25,25,25,25]
scipy.stats.chisquare(obs_ls, exp_ls)

Power_divergenceResult(statistic=6.0, pvalue=0.11161022509471265)

In [9]:
obs_ls = [4,13,7]
exp_ls = [8]*3
scipy.stats.chisquare(obs_ls, exp_ls)

Power_divergenceResult(statistic=5.25, pvalue=0.07243975703425146)

In [13]:
obs_ls = [345, 125, 30]
s_n = sum(obs_ls)
exp_prop_ls = [0.66, 0.25, 0.09]
assert sum(exp_prop_ls) == 1
exp_ls = [expr_prop * s_n for expr_prop in exp_prop_ls]

print(f"obs_ls = {obs_ls}")
print(f"exp_ls = {exp_ls}")

scipy.stats.chisquare(obs_ls, exp_ls)

obs_ls = [345, 125, 30]
exp_ls = [330.0, 125.0, 45.0]


Power_divergenceResult(statistic=5.681818181818182, pvalue=0.058372575858237734)

In [14]:
obs_ls = [75,120,90,15]
s_n = sum(obs_ls)
exp_prop_ls = [0.25,0.4,0.25,0.1]
assert sum(exp_prop_ls) == 1
exp_ls = [expr_prop * s_n for expr_prop in exp_prop_ls]

print(f"obs_ls = {obs_ls}")
print(f"exp_ls = {exp_ls}")

scipy.stats.chisquare(obs_ls, exp_ls)

obs_ls = [75, 120, 90, 15]
exp_ls = [75.0, 120.0, 75.0, 30.0]


Power_divergenceResult(statistic=10.5, pvalue=0.014760897143990665)

In [16]:
obs_ls = [16,11,16,18,19]
s_n = sum(obs_ls)
exp_prop_ls = [0.2, 0.25, 0.2, 0.2, 0.15]
assert sum(exp_prop_ls) == 1
exp_ls = [expr_prop * s_n for expr_prop in exp_prop_ls]

print(f"obs_ls = {obs_ls}")
print(f"exp_ls = {exp_ls}")

scipy.stats.chisquare(obs_ls, exp_ls)

obs_ls = [16, 11, 16, 18, 19]
exp_ls = [16.0, 20.0, 16.0, 16.0, 12.0]


Power_divergenceResult(statistic=8.383333333333333, pvalue=0.07850351401595175)

In [18]:
obs_ls = [4,13,7]
exp_ls = [8] * 3

print(f"obs_ls = {obs_ls}")
print(f"exp_ls = {exp_ls}")

scipy.stats.chisquare(obs_ls, exp_ls)

obs_ls = [4, 13, 7]
exp_ls = [8, 8, 8]


Power_divergenceResult(statistic=5.25, pvalue=0.07243975703425146)

In [35]:
obs_m = np.array(
    [
        [16,30,14],
        [27,23,10],
        [29,16,15],
    ]
)

obs_m

exp_m = np.array(
    [
        [24,23,13],
        [24,23,13],
        [24,23,13]
    ]
)

exp_m

df = (obs_m.shape[0] - 1) * (obs_m.shape[1] - 1)

scipy.stats.chisquare(obs_m, exp_m, axis=None, ddof=df)
1 - scipy.stats.chi2.cdf(scipy.stats.chisquare(obs_m, exp_m, axis=None).statistic, df=df)

array([[16, 30, 14],
       [27, 23, 10],
       [29, 16, 15]])

array([[24, 23, 13],
       [24, 23, 13],
       [24, 23, 13]])

Power_divergenceResult(statistic=9.421125975473801, pvalue=0.05139340757061303)

In [36]:
obs_m = np.array(
    [
        [6,78],
        [9,55],
        [15,133],
        [6,58],
    ]
)

obs_m

exp_m = np.array(
    [
        [8.4, 75.6],
        [6.4,57.6],
        [14.8,133.2],
        [6.4,57.6],
    ]
)

exp_m

df = (obs_m.shape[0] - 1) * (obs_m.shape[1] - 1)
print(f"df = {df}")

scipy.stats.chisquare(obs_m, exp_m, axis=None, ddof=df)

1 - scipy.stats.chi2.cdf(scipy.stats.chisquare(obs_m, exp_m, axis=None).statistic, df=df)

array([[  6,  78],
       [  9,  55],
       [ 15, 133],
       [  6,  58]])

array([[  8.4,  75.6],
       [  6.4,  57.6],
       [ 14.8, 133.2],
       [  6.4,  57.6]])

df = 3


Power_divergenceResult(statistic=1.9662966537966542, pvalue=0.7419579705258157)

In [37]:
obs_m = np.array(
    [
        [6,20,94],
        [10,13,97],
        [20,33,307],
    ]
)

obs_m

exp_m = np.array(
    [
        [7.2,13.2,99.6],
        [7.2,13.2,99.6],
        [21.6,39.6,298.8],
    ]
)

exp_m

df = (obs_m.shape[0] - 1) * (obs_m.shape[1] - 1)
print(f"df = {df}")

scipy.stats.chisquare(obs_m, exp_m, axis=None, ddof=df)

1 - scipy.stats.chi2.cdf(scipy.stats.chisquare(obs_m, exp_m, axis=None).statistic, df=df)

array([[  6,  20,  94],
       [ 10,  13,  97],
       [ 20,  33, 307]])

array([[  7.2,  13.2,  99.6],
       [  7.2,  13.2,  99.6],
       [ 21.6,  39.6, 298.8]])

df = 4


Power_divergenceResult(statistic=6.621232404364934, pvalue=0.1573102454361324)

In [38]:
obs_m = np.array(
    [
        [48,64],
        [33,27],
        [19,9],
    ]
)

obs_m

exp_m = np.array(
    [
        [56,56],
        [30,30],
        [14,14],
    ]
)

exp_m

df = (obs_m.shape[0] - 1) * (obs_m.shape[1] - 1)
print(f"df = {df}")

scipy.stats.chisquare(obs_m, exp_m, axis=None, ddof=df)

1 - scipy.stats.chi2.cdf(scipy.stats.chisquare(obs_m, exp_m, axis=None).statistic, df=df)

array([[48, 64],
       [33, 27],
       [19,  9]])

array([[56, 56],
       [30, 30],
       [14, 14]])

df = 2


Power_divergenceResult(statistic=6.457142857142856, pvalue=0.09136809359628524)